version: '3'

services:
  cobra-e2e-tests-dind:
    container_name: cobra-e2e-tests-dind
    restart: always
    hostname: cobra-e2e-tests-dind
    # image: docker:23.0.0-dind
    image: docker:20.10.21-dind
    privileged: true
    dns: 8.8.8.8
    environment:
      DOCKER_TLS_CERTDIR: "/certs"
      DOCKER_TLS_VERIFY: 1
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - shared:/shared
    networks:
      - cobra

  cobra-e2e-tests:
    container_name: cobra-e2e-tests
    restart: always
    hostname: cobra-e2e-tests
    build: tests
    depends_on:
      - cobra-e2e-tests-dind
    volumes: 
      - docker-certs-client:/root/.docker:ro
      - shared:/shared
    environment:
      DOCKER_HOST: "tcp://cobra-e2e-tests-dind:2376"
      DOCKER_TLS_VERIFY: 1
      DOCKER_CERT_PATH: /root/.docker
      PYTHONPATH: /test
    networks:
      - cobra
    # entrypoint:
    #   - dumb-init
    #   - bash 
    #   - -c 
    #   - "./wait-for-it.sh cobra-e2e-tests-dind:2376 -t 30; pytest"

volumes:
  docker-certs-ca:
  docker-certs-client:
  shared:

networks:
  cobra: